apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"globomantics-app-dev","namespace":"argocd"},"spec":{"destination":{"namespace":"globomantics-dev","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"apps/dev","repoURL":"https://github.com/CodeWithPraveen/ps-implementing-gitops.git","targetRevision":"HEAD"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2025-11-13T21:14:36Z"
  generation: 83
  name: globomantics-app-dev
  namespace: argocd
  resourceVersion: "7603"
  uid: 44bbafa1-a71c-4141-a9db-7cd524be7cbb
spec:
  destination:
    namespace: globomantics-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/dev
    repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-11-13T21:14:50Z"
    status: Healthy
  history:
  - deployStartedAt: "2025-11-13T21:14:38Z"
    deployedAt: "2025-11-13T21:14:39Z"
    id: 0
    initiatedBy:
      automated: true
    revision: e1c81d68b5594851fa3840f3b9162190133a51b3
    source:
      path: apps/dev
      repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
      targetRevision: HEAD
  - deployStartedAt: "2025-11-13T22:16:38Z"
    deployedAt: "2025-11-13T22:16:39Z"
    id: 1
    initiatedBy:
      username: admin
    revision: e1c81d68b5594851fa3840f3b9162190133a51b3
    source:
      path: apps/dev
      repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
      targetRevision: HEAD
  - deployStartedAt: "2025-11-13T22:20:54Z"
    deployedAt: "2025-11-13T22:20:55Z"
    id: 2
    initiatedBy:
      username: admin
    revision: e1c81d68b5594851fa3840f3b9162190133a51b3
    source:
      path: apps/dev
      repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
      targetRevision: HEAD
  - deployStartedAt: "2025-11-13T22:27:57Z"
    deployedAt: "2025-11-13T22:27:58Z"
    id: 3
    initiatedBy:
      username: admin
    revision: e1c81d68b5594851fa3840f3b9162190133a51b3
    source:
      path: apps/dev
      repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
      targetRevision: HEAD
  - deployStartedAt: "2025-11-13T22:34:04Z"
    deployedAt: "2025-11-13T22:34:05Z"
    id: 4
    initiatedBy:
      username: admin
    revision: e1c81d68b5594851fa3840f3b9162190133a51b3
    source:
      path: apps/dev
      repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
      targetRevision: HEAD
  - deployStartedAt: "2025-11-13T22:40:22Z"
    deployedAt: "2025-11-13T22:40:22Z"
    id: 5
    initiatedBy:
      username: admin
    revision: e1c81d68b5594851fa3840f3b9162190133a51b3
    source:
      path: apps/dev
      repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
      targetRevision: HEAD
  - deployStartedAt: "2025-11-13T22:40:48Z"
    deployedAt: "2025-11-13T22:40:48Z"
    id: 6
    initiatedBy:
      username: admin
    revision: e1c81d68b5594851fa3840f3b9162190133a51b3
    source:
      path: apps/dev
      repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
      targetRevision: HEAD
  - deployStartedAt: "2025-11-13T22:45:09Z"
    deployedAt: "2025-11-13T22:45:10Z"
    id: 7
    initiatedBy:
      username: admin
    revision: e1c81d68b5594851fa3840f3b9162190133a51b3
    source:
      path: apps/dev
      repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2025-11-13T22:45:10Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: e1c81d68b5594851fa3840f3b9162190133a51b3
        source:
          path: apps/dev
          repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
          targetRevision: HEAD
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2025-11-13T22:45:09Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/globomantics-dev unchanged
        name: globomantics-dev
        namespace: globomantics-dev
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/globomantics-service unchanged
        name: globomantics-service
        namespace: globomantics-dev
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - nginx:latest
        kind: Deployment
        message: deployment.apps/globomantics-app unchanged
        name: globomantics-app
        namespace: globomantics-dev
        status: Synced
        syncPhase: Sync
        version: v1
      revision: e1c81d68b5594851fa3840f3b9162190133a51b3
      source:
        path: apps/dev
        repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
        targetRevision: HEAD
  reconciledAt: "2025-11-13T22:45:10Z"
  resourceHealthSource: appTree
  resources:
  - kind: Namespace
    name: globomantics-dev
    status: Synced
    version: v1
  - kind: Service
    name: globomantics-service
    namespace: globomantics-dev
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: globomantics-app
    namespace: globomantics-dev
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Kustomize
  summary:
    images:
    - nginx:latest
  sync:
    comparedTo:
      destination:
        namespace: globomantics-dev
        server: https://kubernetes.default.svc
      source:
        path: apps/dev
        repoURL: https://github.com/CodeWithPraveen/ps-implementing-gitops.git
        targetRevision: HEAD
    revision: e1c81d68b5594851fa3840f3b9162190133a51b3
    status: Synced
